"""job stage candidate application activity

Revision ID: 2e558f969ca0
Revises: 5580eabe8ece
Create Date: 2026-05-15 12:46:06.835073

"""
from collections.abc import Sequence

import sqlalchemy as sa  # noqa: F401
from sqlalchemy.dialects import postgresql

from alembic import op  # noqa: F401
from src.db.rls import disable_rls_sql, enable_rls_sql

DOMAIN_TABLES = ("job", "stage", "candidate", "application", "activity")

# revision identifiers, used by Alembic.
revision: str = '2e558f969ca0'
down_revision: str | None = '5580eabe8ece'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_tenant_id'), 'candidate', ['tenant_id'], unique=False)
    op.create_index('uq_candidate_tenant_cpf_alive', 'candidate', ['tenant_id', 'cpf'], unique=True, postgresql_where=sa.text('cpf IS NOT NULL AND deleted_at IS NULL'))
    op.create_index('uq_candidate_tenant_email_alive', 'candidate', ['tenant_id', sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('job', 'candidate', 'application', name='activity_entity_type_enum'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_tenant_entity_created', 'activity', ['tenant_id', 'entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_activity_tenant_id'), 'activity', ['tenant_id'], unique=False)
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('employment_type', sa.Enum('clt', 'pj', 'estagio', 'temp', 'freelancer', name='employment_type_enum'), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'paused', 'closed', name='job_status_enum'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_tenant_id'), 'job', ['tenant_id'], unique=False)
    op.create_index('ix_job_tenant_status_created_at', 'job', ['tenant_id', 'status', 'created_at'], unique=False, postgresql_using='btree')
    op.create_table('stage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('active', 'terminal_hired', 'terminal_rejected', name='stage_kind_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'position', name='uq_stage_job_position')
    )
    op.create_index(op.f('ix_stage_job_id'), 'stage', ['job_id'], unique=False)
    op.create_index(op.f('ix_stage_tenant_id'), 'stage', ['tenant_id'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('current_stage_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'hired', 'rejected', 'withdrawn', name='application_status_enum'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['stage.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'job_id', 'candidate_id', name='uq_app_tenant_job_candidate')
    )
    op.create_index(op.f('ix_application_candidate_id'), 'application', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_job_id'), 'application', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_tenant_id'), 'application', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Grants para a application role (uphiring_app) — criada na migration
    # anterior (5580eabe8ece). Idempotente porque GRANT em tabelas já-grantadas
    # é no-op.
    op.execute(
        "GRANT SELECT, INSERT, UPDATE, DELETE ON job, stage, candidate, application, activity "
        "TO uphiring_app;"
    )

    # RLS: política padrão tenant_id = current_setting('app.current_tenant_id')
    # em todas as 5 tabelas. Stage tem tenant_id próprio (não herda via job)
    # por defesa em profundidade.
    for table in DOMAIN_TABLES:
        for stmt in enable_rls_sql(table):
            op.execute(stmt)


def downgrade() -> None:
    # Reverter RLS antes de dropar as tabelas (DROP TABLE também limpa policies,
    # mas mantemos explícito para simetria do upgrade).
    for table in reversed(DOMAIN_TABLES):
        for stmt in disable_rls_sql(table):
            op.execute(stmt)

    op.execute(
        "REVOKE SELECT, INSERT, UPDATE, DELETE ON job, stage, candidate, application, activity "
        "FROM uphiring_app;"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_tenant_id'), table_name='application')
    op.drop_index(op.f('ix_application_job_id'), table_name='application')
    op.drop_index(op.f('ix_application_candidate_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_stage_tenant_id'), table_name='stage')
    op.drop_index(op.f('ix_stage_job_id'), table_name='stage')
    op.drop_table('stage')
    op.drop_index('ix_job_tenant_status_created_at', table_name='job', postgresql_using='btree')
    op.drop_index(op.f('ix_job_tenant_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_activity_tenant_id'), table_name='activity')
    op.drop_index('ix_activity_tenant_entity_created', table_name='activity')
    op.drop_table('activity')
    op.drop_index('uq_candidate_tenant_email_alive', table_name='candidate', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('uq_candidate_tenant_cpf_alive', table_name='candidate', postgresql_where=sa.text('cpf IS NOT NULL AND deleted_at IS NULL'))
    op.drop_index(op.f('ix_candidate_tenant_id'), table_name='candidate')
    op.drop_table('candidate')
    # ### end Alembic commands ###

    # Drop dos enum types — sa.Enum + create_type=True deixa o tipo pendurado
    # quando a tabela é dropada. Re-aplicar upgrade depois falha com "type
    # already exists" se não limparmos aqui.
    for enum_name in (
        "application_status_enum",
        "stage_kind_enum",
        "job_status_enum",
        "employment_type_enum",
        "activity_entity_type_enum",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
